[versions]
agp = "8.13.1"
annotation = "1.9.1"
kotlin = "2.2.21"
ktfmt = "0.25.0"

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
